# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.5"
manifest_format = "2.0"
project_hash = "bbf5b92886283151baf88e0a954a29c7e4621e99"

[[deps.FBCPoisson]]
path = "."
uuid = "1f0f7e10-245c-4955-b3bf-660f62c508bb"
version = "1.0.0-DEV"
